# Generated by Django 3.2 on 2023-11-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_contact_customer_confidence'),
        ('excustomer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excustomer',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='excustomer',
            name='interested_products',
        ),
        migrations.AddField(
            model_name='excustomer',
            name='interested_products',
            field=models.ManyToManyField(to='app1.ProductType'),
        ),
    ]
