# Generated by Django 3.2 on 2023-11-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excustomer', '0002_auto_20231106_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excustomer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
