# Generated by Django 4.2.4 on 2023-10-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventtype_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtype',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='eventtype',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
