# Generated by Django 4.2.4 on 2023-10-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
