# Generated by Django 4.2.4 on 2023-10-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_customer_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
    ]
