# Generated by Django 4.2.4 on 2023-10-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_customer_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='event.eventtype'),
        ),
    ]
