# Generated by Django 4.2.4 on 2023-10-06 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_customer_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
