# Generated by Django 4.2.4 on 2023-09-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_contact_date_of_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_of_enquiry',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
