# Generated by Django 4.2.4 on 2023-10-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_contact_engage_contact_engaged_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(default='Strings', max_length=200),
        ),
    ]
