# Generated by Django 4.2.4 on 2023-10-05 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_contact_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='engaged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.employee'),
        ),
    ]
