# Generated by Django 4.2.4 on 2023-10-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_contactproduct_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='contactproduct',
            name='product_name',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='contact',
            name='interested_products',
        ),
        migrations.AddField(
            model_name='contact',
            name='interested_products',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
