# Generated by Django 4.2.4 on 2023-10-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_contactproduct_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactProduct',
        ),
    ]
