# Generated by Django 3.2 on 2023-10-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_brandmailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='brandmailer',
            name='attachments',
            field=models.ManyToManyField(to='app1.BrandAttachment'),
        ),
    ]
