# Generated by Django 4.2.7 on 2023-11-22 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_delete_customer'),
        ('app1', '0012_alter_contact_customer_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='ComposeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('attachments', models.ManyToManyField(blank=True, to='app1.composeattachment')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compose_messages', to='event.eventtype')),
            ],
        ),
    ]
