# Generated by Django 4.2.7 on 2023-11-20 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_composeattachment_composemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='composeattachment',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_set', to='app1.composemessage'),
            preserve_default=False,
        ),
    ]
