# Generated by Django 4.2.7 on 2023-11-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_composeattachment_composemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='composemessage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compose_messages', to='app1.producttype'),
        ),
    ]
