# Generated by Django 4.2.7 on 2023-11-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_composeattachment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composeattachment',
            name='message',
        ),
    ]
