# Generated by Django 4.2.7 on 2023-11-27 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_composemessage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCompose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(to='app1.attachment')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.producttype')),
            ],
        ),
    ]
