# Generated by Django 4.2.7 on 2023-11-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_productcompose'),
        ('app1', '0015_remove_composeattachment_message'),
    ]

    operations = [
    ]
