# Generated by Django 4.2.7 on 2023-11-21 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileaddition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscription_details',
        ),
        migrations.AddField(
            model_name='profile',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan_name',
            field=models.CharField(choices=[('1 Month', '1 Month'), ('6 Months', '6 Months'), ('1 Year', '1 Year')], max_length=100),
        ),
    ]
